services:



    liquetsoft_fias.elastic.client_provider:
        class: Liquetsoft\Fias\Elastic\ClientProvider\BuilderProvider
        arguments:
            $hosts: '%liquetsoft_fias.elasticsearch_hosts%'

    Liquetsoft\Fias\Elastic\ClientProvider\ClientProvider:
        alias: liquetsoft_fias.elastic.client_provider



    liquetsoft_fias.elastic.index_builder:
        class: Liquetsoft\Fias\Elastic\IndexBuilder\BaseIndexBuilder
        arguments:
            $clientProvider: '@liquetsoft_fias.elastic.client_provider'

    Liquetsoft\Fias\Elastic\IndexBuilder\IndexBuilder:
        alias: liquetsoft_fias.elastic.index_builder



    Liquetsoft\Fias\Elastic\IndexMapper\AddrObjDivisionIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\AddrObjDivisionIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\AddrObjIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\AddrObjIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\AddrObjTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\AddrObjTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\AdmHierarchyIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\AdmHierarchyIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ApartmentsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ApartmentsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ApartmentTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ApartmentTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\CarplacesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\CarplacesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ChangeHistoryIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ChangeHistoryIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\HousesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\HousesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\HouseTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\HouseTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\MunHierarchyIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\MunHierarchyIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsKindsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsKindsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ObjectLevelsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ObjectLevelsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\OperationTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\OperationTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ParamIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ParamIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ParamTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ParamTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\ReestrObjectsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\ReestrObjectsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\RoomsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\RoomsIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\RoomTypesIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\RoomTypesIndexMapper

    Liquetsoft\Fias\Elastic\IndexMapper\SteadsIndexMapper:
        class: Liquetsoft\Fias\Elastic\IndexMapper\SteadsIndexMapper



    liquetsoft_fias.elastic.index_mapper_registry:
        class: Liquetsoft\Fias\Elastic\IndexMapperRegistry\ArrayIndexMapperRegistry
        arguments:
            $indexMappers:
                Liquetsoft\Fias\Elastic\Entity\AddrObjDivision: '@Liquetsoft\Fias\Elastic\IndexMapper\AddrObjDivisionIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\AddrObj: '@Liquetsoft\Fias\Elastic\IndexMapper\AddrObjIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\AddrObjTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\AddrObjTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\AdmHierarchy: '@Liquetsoft\Fias\Elastic\IndexMapper\AdmHierarchyIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\Apartments: '@Liquetsoft\Fias\Elastic\IndexMapper\ApartmentsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\ApartmentTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\ApartmentTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\Carplaces: '@Liquetsoft\Fias\Elastic\IndexMapper\CarplacesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\ChangeHistory: '@Liquetsoft\Fias\Elastic\IndexMapper\ChangeHistoryIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\Houses: '@Liquetsoft\Fias\Elastic\IndexMapper\HousesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\HouseTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\HouseTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\MunHierarchy: '@Liquetsoft\Fias\Elastic\IndexMapper\MunHierarchyIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\NormativeDocs: '@Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\NormativeDocsKinds: '@Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsKindsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\NormativeDocsTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\NormativeDocsTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\ObjectLevels: '@Liquetsoft\Fias\Elastic\IndexMapper\ObjectLevelsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\OperationTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\OperationTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\Param: '@Liquetsoft\Fias\Elastic\IndexMapper\ParamIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\ParamTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\ParamTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\ReestrObjects: '@Liquetsoft\Fias\Elastic\IndexMapper\ReestrObjectsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\Rooms: '@Liquetsoft\Fias\Elastic\IndexMapper\RoomsIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\RoomTypes: '@Liquetsoft\Fias\Elastic\IndexMapper\RoomTypesIndexMapper'
                Liquetsoft\Fias\Elastic\Entity\SteadsIndex: '@Liquetsoft\Fias\Elastic\IndexMapper\SteadsIndexMapper'

    Liquetsoft\Fias\Elastic\IndexMapperRegistry\IndexMapperRegistry:
        alias: liquetsoft_fias.elastic.index_mapper_registry



    Liquetsoft\Fias\Elastic\Storage\ElasticStorage:
        class: Liquetsoft\Fias\Elastic\Storage\ElasticStorage
        arguments:
            $clientProvider: '@liquetsoft_fias.elastic.client_provider'
            $registry: '@liquetsoft_fias.elastic.index_mapper_registry'
            $indexBuilder: '@liquetsoft_fias.elastic.index_builder'
            $insertBatch: '%liquetsoft_fias.insert_batch_count%'
        tags:
            - { name: 'liquetsoft_fias.storage' }



    liquetsoft_fias.elastic.repository:
        class: Liquetsoft\Fias\Elastic\ElasticSearchRepository\BaseElasticSearchRepository
        arguments:
            $clientProvider: '@liquetsoft_fias.elastic.client_provider'
            $denormalizer: '@serializer'

    Liquetsoft\Fias\Elastic\ElasticSearchRepository\ElasticSearchRepository:
        alias: liquetsoft_fias.elastic.repository



    liquetsoft_fias.elastic.create_indicies_command:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\CreateElasticIndiciesCommand
        arguments:
            $entityManager: '@liquetsoft_fias.entity_manager.service'
            $registry: '@liquetsoft_fias.elastic.index_mapper_registry'
            $builder: '@liquetsoft_fias.elastic.index_builder'
        tags:
            - { name: 'console.command' }
