services:



    liquetsoft_fias.fs.service:
        class: Marvin255\FileSystemHelper\FileSystemHelperImpl

    Marvin255\FileSystemHelper\FileSystemHelper:
        alias: liquetsoft_fias.fs.service



    liquetsoft_fias.http_transport.service:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\HttpTransport\HttpTransportSymfony
        arguments:
            - '@http_client'

    Liquetsoft\Fias\Component\HttpTransport\HttpTransport:
        alias: liquetsoft_fias.http_transport.service



    liquetsoft_fias.informer.service:
        class: Liquetsoft\Fias\Component\FiasInformer\FiasInformerImpl
        arguments:
            - '@liquetsoft_fias.http_transport.service'

    Liquetsoft\Fias\Component\FiasInformer\FiasInformer:
        alias: liquetsoft_fias.informer.service



    liquetsoft_fias.status_checker.service:
        class: Liquetsoft\Fias\Component\FiasStatusChecker\FiasStatusCheckerImpl
        arguments:
            - '@liquetsoft_fias.http_transport.service'
            - '@liquetsoft_fias.informer.service'

    Liquetsoft\Fias\Component\FiasStatusChecker\FiasStatusChecker:
        alias: liquetsoft_fias.status_checker.service



    liquetsoft_fias.downloader.service:
        class: Liquetsoft\Fias\Component\Downloader\DownloaderImpl
        arguments:
            - '@liquetsoft_fias.http_transport.service'
            - '%liquetsoft_fias.download_retry_attempts%'

    Liquetsoft\Fias\Component\Downloader\Downloader:
        alias: liquetsoft_fias.downloader.service



    liquetsoft_fias.unpacker.service:
        class: Liquetsoft\Fias\Component\Unpacker\UnpackerZip

    Liquetsoft\Fias\Component\Unpacker\Unpacker:
        alias: liquetsoft_fias.unpacker.service



    liquetsoft_fias.filter.files_filter:
        class: Liquetsoft\Fias\Component\Filter\RegexpFilter
        arguments:
            - '%liquetsoft_fias.files_filter%'



    liquetsoft_fias.file_selector.archive_selector:
        class: Liquetsoft\Fias\Component\FiasFileSelector\FiasFileSelectorArchive
        arguments:
            - '@liquetsoft_fias.unpacker.service'
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.filter.files_filter'
        tags:
            - { name: 'liquetsoft_fias.file_selector' }

    liquetsoft_fias.file_selector.dir_selector:
        class: Liquetsoft\Fias\Component\FiasFileSelector\FiasFileSelectorDir
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.fs.service'
            - '@liquetsoft_fias.filter.files_filter'
        tags:
            - { name: 'liquetsoft_fias.file_selector' }

    liquetsoft_fias.file_selector.service:
        class: Liquetsoft\Fias\Component\FiasFileSelector\FiasFileSelectorComposite
        arguments:
            - !tagged_iterator liquetsoft_fias.file_selector

    Liquetsoft\Fias\Component\FiasFileSelector\FiasFileSelector:
        alias: liquetsoft_fias.file_selector.service



    liquetsoft_fias.xml_reader.service:
        class: Liquetsoft\Fias\Component\XmlReader\BaseXmlReader

    Liquetsoft\Fias\Component\XmlReader\XmlReader:
        alias: liquetsoft_fias.xml_reader.service



    liquetsoft_fias.serializer.compiled_denormalizer:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Serializer\CompiledEntitesDenormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.uuid_denormalizer:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Serializer\FiasUuidNormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.pipeline_state_normalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasPipelineStateNormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.pipeline_state_denormalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasPipelineStateDenormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.unpacker_file_denormalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasUnpackerFileDenormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.unpacker_file_normalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasUnpackerFileNormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.file_denormalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasFileDenormalizer
        tags:
            - { name: 'serializer.normalizer' }

    liquetsoft_fias.serializer.file_normalizer:
        class: Liquetsoft\Fias\Component\Serializer\FiasFileNormalizer
        tags:
            - { name: 'serializer.normalizer' }



    liquetsoft_fias.entity_registry.service:
        class: Liquetsoft\Fias\Component\EntityRegistry\PhpArrayFileRegistry
        arguments:
            - '%liquetsoft_fias.registry_path%'

    Liquetsoft\Fias\Component\EntityRegistry\EntityRegistry:
        alias: liquetsoft_fias.entity_registry.service



    liquetsoft_fias.entity_manager.service:
        class: Liquetsoft\Fias\Component\EntityManager\BaseEntityManager
        arguments:
            - '@liquetsoft_fias.entity_registry.service'
            - '%liquetsoft_fias.entity_bindings%'

    Liquetsoft\Fias\Component\EntityManager\EntityManager:
        alias: liquetsoft_fias.entity_manager.service



    liquetsoft_fias.storage.service:
        class: Liquetsoft\Fias\Component\Storage\CompositeStorage
        arguments:
            $internalStorages: !tagged_iterator liquetsoft_fias.storage

    Liquetsoft\Fias\Component\Storage\Storage:
        alias: liquetsoft_fias.storage.service

    liquetsoft_fias.storage.doctrine_storage:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Storage\BulkInsertDoctrineStorage
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%liquetsoft_fias.insert_batch_count%'
            - '@logger'
        tags:
            - { name: 'liquetsoft_fias.storage' }



    liquetsoft_fias.version_manager.service:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\VersionManager\DoctrineVersionManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%liquetsoft_fias.version_manager_entity%'

    Liquetsoft\Fias\Component\VersionManager\VersionManager:
        alias: liquetsoft_fias.version_manager.service



    liquetsoft_fias.files.paralleling_dispatcher:
        class: Liquetsoft\Fias\Component\FilesDispatcher\FilesDispatcherImpl
        arguments:
            $entityManager: '@liquetsoft_fias.entity_manager.service'

    Liquetsoft\Fias\Component\FilesDispatcher\FilesDispatcher:
        alias: liquetsoft_fias.files.paralleling_dispatcher



    liquetsoft_fias.task.cleanup:
        class: Liquetsoft\Fias\Component\Pipeline\Task\CleanupTask
        arguments:
            - '@liquetsoft_fias.fs.service'

    liquetsoft_fias.task.cleanup_files:
        class: Liquetsoft\Fias\Component\Pipeline\Task\CleanupFilesUnpacked
        arguments:
            - '@liquetsoft_fias.fs.service'

    liquetsoft_fias.task.status.check:
        class: Liquetsoft\Fias\Component\Pipeline\Task\CheckStatusTask
        arguments:
            - '@liquetsoft_fias.status_checker.service'

    liquetsoft_fias.task.prepare.folder:
        class: Liquetsoft\Fias\Component\Pipeline\Task\PrepareFolderTask
        arguments:
            - '%liquetsoft_fias.temp_dir%'
            - '@liquetsoft_fias.fs.service'

    liquetsoft_fias.task.inform.full:
        class: Liquetsoft\Fias\Component\Pipeline\Task\InformFullTask
        arguments:
            - '@liquetsoft_fias.informer.service'

    liquetsoft_fias.task.inform.delta:
        class: Liquetsoft\Fias\Component\Pipeline\Task\InformDeltaTask
        arguments:
            - '@liquetsoft_fias.informer.service'

    liquetsoft_fias.task.download:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DownloadTask
        arguments:
            - '@liquetsoft_fias.downloader.service'

    liquetsoft_fias.task.unpack:
        class: Liquetsoft\Fias\Component\Pipeline\Task\UnpackTask
        arguments:
            - '@liquetsoft_fias.unpacker.service'

    liquetsoft_fias.task.data.truncate:
        class: Liquetsoft\Fias\Component\Pipeline\Task\TruncateTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.storage.service'

    liquetsoft_fias.task.data.select_files:
        class: Liquetsoft\Fias\Component\Pipeline\Task\SelectFilesToProceedTask
        arguments:
            - '@liquetsoft_fias.file_selector.service'

    liquetsoft_fias.task.data.insert:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DataInsertTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.xml_reader.service'
            - '@liquetsoft_fias.storage.service'
            - '@serializer'

    liquetsoft_fias.task.data.delete:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DataDeleteTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.xml_reader.service'
            - '@liquetsoft_fias.storage.service'
            - '@serializer'

    liquetsoft_fias.task.data.upsert:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DataUpsertTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.xml_reader.service'
            - '@liquetsoft_fias.storage.service'
            - '@serializer'

    liquetsoft_fias.task.version.get:
        class: Liquetsoft\Fias\Component\Pipeline\Task\VersionGetTask
        arguments:
            - '@liquetsoft_fias.version_manager.service'

    liquetsoft_fias.task.version.set:
        class: Liquetsoft\Fias\Component\Pipeline\Task\VersionSetTask
        arguments:
            - '@liquetsoft_fias.version_manager.service'

    liquetsoft_fias.task.process_switcher_install:
        class: Liquetsoft\Fias\Component\Pipeline\Task\ProcessSwitchTask
        arguments:
            $filesDispatcher: '@liquetsoft_fias.files.paralleling_dispatcher'
            $serializer: '@serializer'
            $pathToBin: '%liquetsoft_fias.path_to_console_bin%'
            $commandName: '%liquetsoft_fias.instal_running_command%'
            $numberOfParallel: '%liquetsoft_fias.number_of_parallel%'

    liquetsoft_fias.task.process_switcher_update:
        class: Liquetsoft\Fias\Component\Pipeline\Task\ProcessSwitchTask
        arguments:
            $filesDispatcher: '@liquetsoft_fias.files.paralleling_dispatcher'
            $serializer: '@serializer'
            $pathToBin: '%liquetsoft_fias.path_to_console_bin%'
            $commandName: '%liquetsoft_fias.update_running_command%'
            $numberOfParallel: '%liquetsoft_fias.number_of_parallel%'

    liquetsoft_fias.task.apply_nested_pipeline_to_file:
        class: Liquetsoft\Fias\Component\Pipeline\Task\ApplyNestedPipelineToFileTask
        arguments:
            - '@liquetsoft_fias.pipe.proceed_file'



    liquetsoft_fias.pipe.proceed_file:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.unpack'
                - '@liquetsoft_fias.task.data.insert'
                - '@liquetsoft_fias.task.data.delete'
            $cleanupTask: '@liquetsoft_fias.task.cleanup_files'
            $logger: '@logger'

    liquetsoft_fias.pipe.install:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.status.check'
                - '@liquetsoft_fias.task.prepare.folder'
                - '@liquetsoft_fias.task.inform.full'
                - '@liquetsoft_fias.task.download'
                - '@liquetsoft_fias.task.data.truncate'
                - '@liquetsoft_fias.task.data.select_files'
                - '@liquetsoft_fias.task.process_switcher_install'
                - '@liquetsoft_fias.task.version.set'
            $cleanupTask: '@liquetsoft_fias.task.cleanup'
            $logger: '@logger'

    liquetsoft_fias.pipe.install_from_folder:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.data.truncate'
                - '@liquetsoft_fias.task.data.select_files'
                - '@liquetsoft_fias.task.process_switcher_install'
            $cleanupTask: null
            $logger: '@logger'

    liquetsoft_fias.pipe.install_parallel_running:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.apply_nested_pipeline_to_file'
            $cleanupTask: null
            $logger: '@logger'

    liquetsoft_fias.pipe.update:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.status.check'
                - '@liquetsoft_fias.task.version.get'
                - '@liquetsoft_fias.task.prepare.folder'
                - '@liquetsoft_fias.task.inform.delta'
                - '@liquetsoft_fias.task.download'
                - '@liquetsoft_fias.task.data.select_files'
                - '@liquetsoft_fias.task.process_switcher_update'
                - '@liquetsoft_fias.task.version.set'
            $cleanupTask: '@liquetsoft_fias.task.cleanup'
            $logger: '@logger'

    liquetsoft_fias.pipe.update_from_folder:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.data.select_files'
                - '@liquetsoft_fias.task.process_switcher_update'
            $cleanupTask: null
            $logger: '@logger'

    liquetsoft_fias.pipe.update_parallel_running:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.apply_nested_pipeline_to_file'
            $cleanupTask: null
            $logger: '@logger'



    liquetsoft_fias.command.install:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\InstallParallelCommand
        arguments:
            - '@liquetsoft_fias.pipe.install'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.install_from_folder:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\InstallFromFolderCommand
        arguments:
            - '@liquetsoft_fias.pipe.install_from_folder'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.install_parallel_running:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\InstallParallelRunningCommand
        arguments:
            - '@liquetsoft_fias.pipe.install_parallel_running'
            - '@serializer'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.truncate:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\TruncateCommand
        arguments:
            - '@liquetsoft_fias.task.data.truncate'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.update:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\UpdateCommand
        arguments:
            - '@liquetsoft_fias.pipe.update'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.update_from_folder:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\UpdateFromFolderCommand
        arguments:
            - '@liquetsoft_fias.pipe.update_from_folder'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.update_parallel_running:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\UpdateParallelRunningCommand
        arguments:
            - '@liquetsoft_fias.pipe.update_parallel_running'
            - '@serializer'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.versions:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\VersionsCommand
        arguments:
            - '@liquetsoft_fias.informer.service'
            - '@liquetsoft_fias.version_manager.service'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.version_set:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\VersionSetCommand
        arguments:
            - '@liquetsoft_fias.informer.service'
            - '@liquetsoft_fias.version_manager.service'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.download:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\DownloadCommand
        arguments:
            - '@liquetsoft_fias.downloader.service'
            - '@liquetsoft_fias.unpacker.service'
            - '@liquetsoft_fias.informer.service'
            - '@liquetsoft_fias.fs.service'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.status:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\StatusCheckCommand
        arguments:
            - '@liquetsoft_fias.status_checker.service'
        tags:
            - { name: 'console.command' }
