name: liquetsoft_fias

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  build:
    name: Liquetsoft FIAS (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0']
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Check PHP Version
      run: php -v
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run test suite
      run: composer run-script test
    - name: Run linters
      run: composer run-script linter


  symfony:
    name: Testing installation to symfony (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: symfony
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: symfony
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql, curl
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Install Symfony
        run: |
          composer create-project laravel/laravel example-app
      - name: Install FIAS
        run: |
          unzip ./Tests/Pipeline/_fixtures/install_AddressObject.zip -d ./example-app/fias-data-install
          unzip ./Tests/Pipeline/_fixtures/update_AddressObject.zip -d ./example-app/fias-data-update
          cd example-app
          composer req "liquetsoft/fias-symfony:dev-${{ github.head_ref }}"
          cp ./../Tests/MockEntities/SymfonyTestAddrObj.php src/Entity/AddrObj.php
          cp ./../Tests/MockEntities/SymfonyTestFiasVersion.php src/Entity/FiasVersion.php
          echo "liquetsoft_fias:" > config/packages/liquetsoft_fias.yaml
          echo "    version_manager_entity: App\Entity\FiasVersion" >> config/packages/liquetsoft_fias.yaml
          echo "    entity_bindings:" >> config/packages/liquetsoft_fias.yaml
          echo "        ADDR_OBJ: App\Entity\AddrObj" >> config/packages/liquetsoft_fias.yaml
          echo "APP_ENV=dev" > .env
          echo "APP_SECRET=test" >> .env
          echo "mysql://root:password@127.0.0.1:3306/symfony?serverVersion=5.7" >> .env
          php bin/console cache:clear
          php bin/console doctrine:schema:create -n
      - name: Test FIAS
        run: |
          cd example-app
          php bin/console liquetsoft:fias:truncate
          php bin/console liquetsoft:fias:install_from_folder ./fias-data-install
          php bin/console liquetsoft:fias:update_from_folder ./fias-data-update
          php bin/console liquetsoft:fias:status
          php bin/console liquetsoft:fias:versions
